# Generated by Django 5.0.6 on 2024-08-21 05:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='car_user',
        ),
        migrations.AddField(
            model_name='car',
            name='buyers',
            field=models.ManyToManyField(blank=True, related_name='purchased_cars', to=settings.AUTH_USER_MODEL),
        ),
    ]
